// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0d99fxEdKXPZk_Ovl7ewxbgjLn4sQaJw',
    appId: '1:454375270921:web:4a6d9e37e43ca5703666d8',
    messagingSenderId: '454375270921',
    projectId: 'portfolio-7ea28',
    authDomain: 'portfolio-7ea28.firebaseapp.com',
    storageBucket: 'portfolio-7ea28.firebasestorage.app',
    measurementId: 'G-B8GWKTBJPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWP7rewrxSbxVfjOf43xuJ1p9YjgLQgio',
    appId: '1:454375270921:android:18b6253634725f843666d8',
    messagingSenderId: '454375270921',
    projectId: 'portfolio-7ea28',
    storageBucket: 'portfolio-7ea28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgJHDqUt-L6lpOutrdAbzcf6lAS2uXncw',
    appId: '1:454375270921:ios:f64e2576256993ad3666d8',
    messagingSenderId: '454375270921',
    projectId: 'portfolio-7ea28',
    storageBucket: 'portfolio-7ea28.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgJHDqUt-L6lpOutrdAbzcf6lAS2uXncw',
    appId: '1:454375270921:ios:f64e2576256993ad3666d8',
    messagingSenderId: '454375270921',
    projectId: 'portfolio-7ea28',
    storageBucket: 'portfolio-7ea28.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0d99fxEdKXPZk_Ovl7ewxbgjLn4sQaJw',
    appId: '1:454375270921:web:0c0f186fde2808663666d8',
    messagingSenderId: '454375270921',
    projectId: 'portfolio-7ea28',
    authDomain: 'portfolio-7ea28.firebaseapp.com',
    storageBucket: 'portfolio-7ea28.firebasestorage.app',
    measurementId: 'G-X0WZRJFMFD',
  );
}
